# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1629933c47c723b0cc233cc3392adaabfacf55c5ef4b22aab308502068382037380d86e59f89fd94c3b77ad42c8e7076b973079d9dcaaeb70fd2c17bb7bb0e23

test:
  secret_key_base: 5c1986589690363b42fe6c2a47741c1a7202244ccf12c14b4a89bfc687418ee49a0e1712e8e43a3fa6771238ab0dc943b16246fbeb931a6b71fee1055ab20ba9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
